// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsZfcv3XC9-w9obL_1A7ulXe1Yxi-rpL8',
    appId: '1:526347371841:web:ebcb89d8019ecad79fcdc0',
    messagingSenderId: '526347371841',
    projectId: 'taskmanager-dc86f',
    authDomain: 'taskmanager-dc86f.firebaseapp.com',
    databaseURL: 'https://taskmanager-dc86f-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanager-dc86f.appspot.com',
    measurementId: 'G-9C22Q7DZFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF7hsCbxsr_aX2U_jvXICAB68mIRauqaA',
    appId: '1:526347371841:android:575b154b45b0c1719fcdc0',
    messagingSenderId: '526347371841',
    projectId: 'taskmanager-dc86f',
    databaseURL: 'https://taskmanager-dc86f-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanager-dc86f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK2xGJF7sOfs9oz77WucUYd3nK6fii1v8',
    appId: '1:526347371841:ios:986d9ac5395c471b9fcdc0',
    messagingSenderId: '526347371841',
    projectId: 'taskmanager-dc86f',
    databaseURL: 'https://taskmanager-dc86f-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanager-dc86f.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK2xGJF7sOfs9oz77WucUYd3nK6fii1v8',
    appId: '1:526347371841:ios:986d9ac5395c471b9fcdc0',
    messagingSenderId: '526347371841',
    projectId: 'taskmanager-dc86f',
    databaseURL: 'https://taskmanager-dc86f-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanager-dc86f.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsZfcv3XC9-w9obL_1A7ulXe1Yxi-rpL8',
    appId: '1:526347371841:web:555f5c7cf241d2cc9fcdc0',
    messagingSenderId: '526347371841',
    projectId: 'taskmanager-dc86f',
    authDomain: 'taskmanager-dc86f.firebaseapp.com',
    databaseURL: 'https://taskmanager-dc86f-default-rtdb.firebaseio.com',
    storageBucket: 'taskmanager-dc86f.appspot.com',
    measurementId: 'G-EJZJK80CHL',
  );
}
